<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>ru.ifmo</groupId>
    <artifactId>jmeter-load-test</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <jmeter.version>5.6.3</jmeter.version>
        <jmeter.test.file>load-test.jmx</jmeter.test.file>
        <host>localhost</host>
        <port>49203</port>
        <token></token>
        <userId></userId>
        <config>1</config>
        <threads>14</threads>
        <rampUp>60</rampUp>
        <duration>300</duration>
        <throughput>560.0</throughput>
        <maxResponseTime>890</maxResponseTime>
    </properties>



    <build>
        <plugins>
            <plugin>
                <groupId>com.lazerycode.jmeter</groupId>
                <artifactId>jmeter-maven-plugin</artifactId>
                <version>3.8.0</version>

                <configuration>
                    <testFilesDirectory>${project.basedir}/src/test/jmeter</testFilesDirectory>
                    <resultsDirectory>${project.basedir}/results/load-test-${config}</resultsDirectory>
                    <generateReports>false</generateReports>
                    <jmeterVersion>${jmeter.version}</jmeterVersion>
                    <testFilesIncluded>
                        <jMeterTestFile>${jmeter.test.file}</jMeterTestFile>
                    </testFilesIncluded>

                    <propertiesUser>
                        <host>${host}</host>
                        <port>${port}</port>
                        <token>${token}</token>
                        <userId>${userId}</userId>
                        <config>${config}</config>
                        <threads>${threads}</threads>
                        <rampUp>${rampUp}</rampUp>
                        <duration>${duration}</duration>
                        <throughput>${throughput}</throughput>
                        <maxResponseTime>${maxResponseTime}</maxResponseTime>
                    </propertiesUser>
                </configuration>

                <executions>
                    <execution>
                        <id>configuration</id>
                        <goals>
                            <goal>configure</goal>
                        </goals>
                    </execution>

                    <execution>
                        <id>jmeter-tests</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>jmeter</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>